### ISSUE TITLE
UI Fix for Countries Dropdown on Send link to Phone

### ISSUE THREAD

**Issue by Claire-Bear** [ntls-io/nautilus-wallet#213]
The issue is on the KYC where you get the option to send a link via sms to your phone to continue the verification process. 
You are given the option to select your country (for country code) and then enter your number. These are both white text over white background which makes it invisible to the user.
![image](https://user-images.githubusercontent.com/52410656/167351058-b74b25e9-515f-4204-96c2-42326589d961.png)
![image](https://user-images.githubusercontent.com/52410656/167351092-abb0de78-b9a0-4cb1-b4a8-5232d028a568.png)

**Comment by PiDelport** [comment]
Resources for this issue:

1. https://github.com/onfido/onfido-sdk-ui/blob/development/UI_CUSTOMIZATION.md documents some of the variables that the widget officially supports customising: that should be our first stop to try and set these colours.

2. However, not every element is reachable through those variables yet. For those, we can reach in with override styles in [onfido-widget.component.scss](https://github.com/ntls-io/nautilus-wallet/blob/main/web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.scss). There's an existing fix for the country selector background colour, which we may need to update or extend for this.
