### ISSUE TITLE
No Balance showing.

### ISSUE THREAD

**Issue by Claire-Bear** [ntls-io/nautilus-wallet#217]
If the wallet has just been opened and there is no balance yet
show 0.00 as the balance

**Comment by Claire-Bear** [comment]
@IscoRuta98 We may need a loading wheel here as well as there seems to be a delay before the balance shows if there are funds.

**Comment by longtomjr** [comment]
Related: #220

**Comment by PiDelport** [comment]
We previously changed this intentionally in the opposite direction, based on feedback that a zero balance was confusing, and should be hidden instead:

- https://github.com/ntls-io/nautilus-wallet/pull/206

We should probably discuss and make a better-documented design decision about this before changing it again, to avoid going back and forth?
