### ISSUE TITLE
KYC Mobile | Cannot upload from gallery

### ISSUE THREAD

**Issue by Claire-Bear** [ntls-io/nautilus-wallet#222]
It does not give me the option to upload from the gallery on Mobile. The only permission it asks for is to access my camera and does not request permission to access my gallery.

**Comment by PiDelport** [comment]
For which component is this?

(For the Onfido widget, this is an intentional policy choice, depending on which verification is taking place.)

**Comment by PiDelport** [comment]
Here's more about the Onfido flow customization:

- https://developers.onfido.com/guide/sdk-customization#flow-customization

**Comment by longtomjr** [comment]
This is a limitation with the Onfido SDK. Nothing to fix on our side.
