### ISSUE TITLE
Mobile Text Overlap 

### ISSUE THREAD

**Issue by Claire-Bear** [ntls-io/nautilus-wallet#224]
The refresh and logout buttons overlap with the nautilus logo in the middle on mobile.

Perhaps we can put these together in a hamburger menu that slides in from the right. (Open to suggestions).

**Comment by PiDelport** [comment]
This starts happening on extremely narrow (<360 px wide) viewports.

A good way to approach fixing this would be to first define some Storybook stories for the header component at key breakpoint sizes.

**Comment by jongbonga** [comment]
@Claire-Bear we can use icons only buttons

**Comment by longtomjr** [comment]
Closed with: https://github.com/ntls-io/nautilus-wallet/issues/224
