### ISSUE TITLE
Move over to using ASA instead of using Algos directly

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/nautilus-wallet#92]
### Backend Changes:
- [x] Transfer algos from an account previously setup with a balance into the new account, and do a zero value transaction of the ASA to the new account (see https://developer.algorand.org/docs/features/asa/#receiving-an-asset)
  - This should happen before the account participates in any transactions. We can do it on first participation, or on account creation.
  - The transfer of Algos transaction should be created and signed outside of the TEE. In the future this will most likely be done once the KYC process have been completed.
  - The zero value transaction of the ASA should be created and signed inside of the enclave

### Frontend Changes:
- [x] Change the functions currently getting the Algorand balance to get the balance of the ASA
- [x] Update the transaction creation to transact ASA instead of ALGOs

### PRs

- [x] #131 - Minimal support for a single, preconfigured ASA.

**Comment by PiDelport** [comment]
- This should finally be addressed with https://github.com/ntls-io/nautilus-wallet/pull/131 🎉
